"""Deterministic per-100g nutrition data based on USDA FoodData Central SR Legacy.

Every entry is keyed by a canonical normalized name and contains macros plus a
full micronutrient profile.  Zero values are omitted to keep the file concise;
the lookup layer treats missing keys as 0.0.

Source: USDA FoodData Central, SR Legacy & Foundation Foods (public domain).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Ingredient catalog — per 100 g edible portion
# ---------------------------------------------------------------------------

INGREDIENT_CATALOG: dict[str, dict] = {
    # ── Proteins ──────────────────────────────────────────────────────────
    "chicken breast cooked": {
        "calories_kcal": 165.0,
        "protein_g": 31.0,
        "carbs_g": 0.0,
        "fat_g": 3.6,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 15.0,
            "iron_mg": 1.0,
            "magnesium_mg": 29.0,
            "phosphorus_mg": 228.0,
            "potassium_mg": 256.0,
            "sodium_mg": 74.0,
            "zinc_mg": 1.0,
            "copper_mg": 0.05,
            "selenium_mcg": 27.6,
            "vitamin_a_mcg": 6.0,
            "niacin_mg": 13.7,
            "vitamin_b6_mg": 0.6,
            "vitamin_b12_mcg": 0.34,
            "choline_mg": 85.0,
        },
    },
    "salmon atlantic raw": {
        "calories_kcal": 208.0,
        "protein_g": 20.4,
        "carbs_g": 0.0,
        "fat_g": 13.4,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 12.0,
            "iron_mg": 0.8,
            "magnesium_mg": 29.0,
            "phosphorus_mg": 240.0,
            "potassium_mg": 363.0,
            "sodium_mg": 59.0,
            "zinc_mg": 0.64,
            "copper_mg": 0.25,
            "selenium_mcg": 36.5,
            "vitamin_a_mcg": 12.0,
            "vitamin_d_mcg": 11.0,
            "vitamin_e_mg": 3.55,
            "thiamin_mg": 0.23,
            "riboflavin_mg": 0.38,
            "niacin_mg": 8.0,
            "vitamin_b6_mg": 0.64,
            "folate_mcg": 25.0,
            "vitamin_b12_mcg": 3.18,
            "choline_mg": 56.0,
            "omega3_epa_mg": 862.0,
            "omega3_dha_mg": 1104.0,
        },
    },
    "beef ground 85 15 cooked": {
        "calories_kcal": 250.0,
        "protein_g": 25.6,
        "carbs_g": 0.0,
        "fat_g": 15.4,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 18.0,
            "iron_mg": 2.6,
            "magnesium_mg": 21.0,
            "phosphorus_mg": 198.0,
            "potassium_mg": 318.0,
            "sodium_mg": 76.0,
            "zinc_mg": 5.7,
            "copper_mg": 0.08,
            "selenium_mcg": 18.2,
            "vitamin_a_mcg": 3.0,
            "niacin_mg": 5.6,
            "vitamin_b6_mg": 0.37,
            "vitamin_b12_mcg": 2.6,
            "choline_mg": 80.0,
        },
    },
    "tofu firm": {
        "calories_kcal": 144.0,
        "protein_g": 17.3,
        "carbs_g": 2.8,
        "fat_g": 8.7,
        "fiber_g": 2.3,
        "micronutrients": {
            "calcium_mg": 350.0,
            "iron_mg": 5.4,
            "magnesium_mg": 58.0,
            "phosphorus_mg": 190.0,
            "potassium_mg": 237.0,
            "sodium_mg": 14.0,
            "zinc_mg": 2.0,
            "copper_mg": 0.4,
            "manganese_mg": 1.5,
            "selenium_mcg": 17.4,
            "folate_mcg": 29.0,
            "choline_mg": 28.0,
        },
    },
    "shrimp cooked": {
        "calories_kcal": 99.0,
        "protein_g": 24.0,
        "carbs_g": 0.2,
        "fat_g": 0.3,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 70.0,
            "iron_mg": 0.5,
            "magnesium_mg": 39.0,
            "phosphorus_mg": 214.0,
            "potassium_mg": 259.0,
            "sodium_mg": 224.0,
            "zinc_mg": 1.6,
            "copper_mg": 0.26,
            "selenium_mcg": 39.6,
            "vitamin_d_mcg": 0.5,
            "vitamin_e_mg": 1.3,
            "niacin_mg": 2.6,
            "vitamin_b6_mg": 0.1,
            "vitamin_b12_mcg": 1.1,
            "choline_mg": 80.9,
        },
    },
    "pork loin cooked": {
        "calories_kcal": 197.0,
        "protein_g": 27.3,
        "carbs_g": 0.0,
        "fat_g": 8.9,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 5.0,
            "iron_mg": 0.9,
            "magnesium_mg": 26.0,
            "phosphorus_mg": 246.0,
            "potassium_mg": 362.0,
            "sodium_mg": 53.0,
            "zinc_mg": 2.0,
            "selenium_mcg": 41.4,
            "thiamin_mg": 0.9,
            "riboflavin_mg": 0.26,
            "niacin_mg": 7.3,
            "vitamin_b6_mg": 0.54,
            "vitamin_b12_mcg": 0.7,
            "choline_mg": 93.0,
        },
    },
    "turkey breast cooked": {
        "calories_kcal": 135.0,
        "protein_g": 30.1,
        "carbs_g": 0.0,
        "fat_g": 0.7,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 11.0,
            "iron_mg": 0.5,
            "magnesium_mg": 32.0,
            "phosphorus_mg": 230.0,
            "potassium_mg": 293.0,
            "sodium_mg": 50.0,
            "zinc_mg": 1.5,
            "selenium_mcg": 30.2,
            "niacin_mg": 11.8,
            "vitamin_b6_mg": 0.8,
            "vitamin_b12_mcg": 0.4,
            "choline_mg": 90.0,
        },
    },
    "tuna canned in water": {
        "calories_kcal": 116.0,
        "protein_g": 25.5,
        "carbs_g": 0.0,
        "fat_g": 0.8,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 11.0,
            "iron_mg": 1.3,
            "magnesium_mg": 33.0,
            "phosphorus_mg": 217.0,
            "potassium_mg": 237.0,
            "sodium_mg": 338.0,
            "zinc_mg": 0.8,
            "selenium_mcg": 80.4,
            "niacin_mg": 13.3,
            "vitamin_b6_mg": 0.43,
            "vitamin_b12_mcg": 2.22,
            "vitamin_d_mcg": 1.7,
            "choline_mg": 29.3,
        },
    },

    # ── Eggs & Dairy ──────────────────────────────────────────────────────
    "egg whole raw": {
        "calories_kcal": 143.0,
        "protein_g": 12.6,
        "carbs_g": 0.7,
        "fat_g": 9.5,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 56.0,
            "iron_mg": 1.75,
            "magnesium_mg": 12.0,
            "phosphorus_mg": 198.0,
            "potassium_mg": 138.0,
            "sodium_mg": 142.0,
            "zinc_mg": 1.29,
            "copper_mg": 0.07,
            "selenium_mcg": 30.7,
            "vitamin_a_mcg": 160.0,
            "vitamin_d_mcg": 2.0,
            "vitamin_e_mg": 1.05,
            "vitamin_k_mcg": 0.3,
            "thiamin_mg": 0.04,
            "riboflavin_mg": 0.46,
            "niacin_mg": 0.08,
            "vitamin_b6_mg": 0.17,
            "folate_mcg": 47.0,
            "vitamin_b12_mcg": 0.89,
            "choline_mg": 294.0,
        },
    },
    "greek yogurt plain": {
        "calories_kcal": 97.0,
        "protein_g": 9.0,
        "carbs_g": 3.6,
        "fat_g": 5.0,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 110.0,
            "iron_mg": 0.07,
            "magnesium_mg": 11.0,
            "phosphorus_mg": 135.0,
            "potassium_mg": 141.0,
            "sodium_mg": 47.0,
            "zinc_mg": 0.52,
            "selenium_mcg": 9.7,
            "vitamin_a_mcg": 26.0,
            "vitamin_b12_mcg": 0.75,
            "riboflavin_mg": 0.28,
            "choline_mg": 15.0,
        },
    },
    "cottage cheese low fat": {
        "calories_kcal": 72.0,
        "protein_g": 12.4,
        "carbs_g": 2.7,
        "fat_g": 1.0,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 61.0,
            "iron_mg": 0.14,
            "magnesium_mg": 5.0,
            "phosphorus_mg": 134.0,
            "potassium_mg": 86.0,
            "sodium_mg": 406.0,
            "zinc_mg": 0.4,
            "selenium_mcg": 9.4,
            "vitamin_a_mcg": 12.0,
            "vitamin_b12_mcg": 0.43,
            "riboflavin_mg": 0.16,
            "choline_mg": 18.0,
        },
    },
    "milk whole": {
        "calories_kcal": 61.0,
        "protein_g": 3.2,
        "carbs_g": 4.8,
        "fat_g": 3.3,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 113.0,
            "iron_mg": 0.03,
            "magnesium_mg": 10.0,
            "phosphorus_mg": 84.0,
            "potassium_mg": 132.0,
            "sodium_mg": 43.0,
            "zinc_mg": 0.37,
            "selenium_mcg": 3.7,
            "vitamin_a_mcg": 46.0,
            "vitamin_d_mcg": 1.3,
            "vitamin_b12_mcg": 0.45,
            "riboflavin_mg": 0.18,
            "choline_mg": 14.3,
        },
    },
    "cheddar cheese": {
        "calories_kcal": 403.0,
        "protein_g": 24.9,
        "carbs_g": 1.3,
        "fat_g": 33.1,
        "fiber_g": 0.0,
        "micronutrients": {
            "calcium_mg": 721.0,
            "iron_mg": 0.68,
            "magnesium_mg": 28.0,
            "phosphorus_mg": 512.0,
            "potassium_mg": 98.0,
            "sodium_mg": 621.0,
            "zinc_mg": 3.1,
            "selenium_mcg": 13.9,
            "vitamin_a_mcg": 265.0,
            "vitamin_d_mcg": 0.6,
            "vitamin_k_mcg": 2.8,
            "vitamin_b12_mcg": 0.83,
            "riboflavin_mg": 0.38,
            "choline_mg": 16.5,
        },
    },

    # ── Grains & Starches ─────────────────────────────────────────────────
    "rice white cooked": {
        "calories_kcal": 130.0,
        "protein_g": 2.7,
        "carbs_g": 28.2,
        "fat_g": 0.3,
        "fiber_g": 0.4,
        "micronutrients": {
            "calcium_mg": 10.0,
            "iron_mg": 1.2,
            "magnesium_mg": 12.0,
            "phosphorus_mg": 43.0,
            "potassium_mg": 35.0,
            "sodium_mg": 1.0,
            "zinc_mg": 0.49,
            "manganese_mg": 0.47,
            "selenium_mcg": 7.5,
            "thiamin_mg": 0.16,
            "niacin_mg": 1.5,
            "folate_mcg": 58.0,
        },
    },
    "rice brown cooked": {
        "calories_kcal": 112.0,
        "protein_g": 2.3,
        "carbs_g": 23.5,
        "fat_g": 0.8,
        "fiber_g": 1.8,
        "micronutrients": {
            "calcium_mg": 10.0,
            "iron_mg": 0.5,
            "magnesium_mg": 44.0,
            "phosphorus_mg": 83.0,
            "potassium_mg": 79.0,
            "sodium_mg": 5.0,
            "zinc_mg": 0.6,
            "manganese_mg": 0.88,
            "selenium_mcg": 9.8,
            "thiamin_mg": 0.1,
            "niacin_mg": 1.5,
            "vitamin_b6_mg": 0.15,
        },
    },
    "oats": {
        "calories_kcal": 389.0,
        "protein_g": 16.9,
        "carbs_g": 66.3,
        "fat_g": 6.9,
        "fiber_g": 10.6,
        "micronutrients": {
            "calcium_mg": 54.0,
            "iron_mg": 4.7,
            "magnesium_mg": 177.0,
            "phosphorus_mg": 523.0,
            "potassium_mg": 429.0,
            "sodium_mg": 2.0,
            "zinc_mg": 4.0,
            "copper_mg": 0.63,
            "manganese_mg": 4.9,
            "selenium_mcg": 28.9,
            "thiamin_mg": 0.76,
            "riboflavin_mg": 0.14,
            "niacin_mg": 0.96,
            "vitamin_b6_mg": 0.12,
            "folate_mcg": 56.0,
            "choline_mg": 40.4,
        },
    },
    "quinoa cooked": {
        "calories_kcal": 120.0,
        "protein_g": 4.4,
        "carbs_g": 21.3,
        "fat_g": 1.9,
        "fiber_g": 2.8,
        "micronutrients": {
            "calcium_mg": 17.0,
            "iron_mg": 1.5,
            "magnesium_mg": 64.0,
            "phosphorus_mg": 152.0,
            "potassium_mg": 172.0,
            "sodium_mg": 7.0,
            "zinc_mg": 1.1,
            "copper_mg": 0.19,
            "manganese_mg": 0.63,
            "selenium_mcg": 2.8,
            "thiamin_mg": 0.11,
            "riboflavin_mg": 0.11,
            "niacin_mg": 0.41,
            "vitamin_b6_mg": 0.12,
            "folate_mcg": 42.0,
            "vitamin_e_mg": 0.63,
        },
    },
    "bread whole wheat": {
        "calories_kcal": 247.0,
        "protein_g": 13.0,
        "carbs_g": 41.3,
        "fat_g": 3.4,
        "fiber_g": 6.8,
        "micronutrients": {
            "calcium_mg": 107.0,
            "iron_mg": 2.5,
            "magnesium_mg": 75.0,
            "phosphorus_mg": 212.0,
            "potassium_mg": 254.0,
            "sodium_mg": 400.0,
            "zinc_mg": 1.8,
            "manganese_mg": 2.2,
            "selenium_mcg": 35.8,
            "thiamin_mg": 0.4,
            "riboflavin_mg": 0.18,
            "niacin_mg": 4.4,
            "vitamin_b6_mg": 0.18,
            "folate_mcg": 44.0,
        },
    },
    "pasta cooked": {
        "calories_kcal": 158.0,
        "protein_g": 5.8,
        "carbs_g": 30.6,
        "fat_g": 0.9,
        "fiber_g": 1.8,
        "micronutrients": {
            "calcium_mg": 7.0,
            "iron_mg": 1.3,
            "magnesium_mg": 18.0,
            "phosphorus_mg": 58.0,
            "potassium_mg": 44.0,
            "sodium_mg": 1.0,
            "zinc_mg": 0.5,
            "selenium_mcg": 26.4,
            "thiamin_mg": 0.24,
            "riboflavin_mg": 0.14,
            "niacin_mg": 1.7,
            "folate_mcg": 83.0,
        },
    },
    "sweet potato baked": {
        "calories_kcal": 90.0,
        "protein_g": 2.0,
        "carbs_g": 20.7,
        "fat_g": 0.2,
        "fiber_g": 3.3,
        "micronutrients": {
            "calcium_mg": 38.0,
            "iron_mg": 0.7,
            "magnesium_mg": 27.0,
            "phosphorus_mg": 54.0,
            "potassium_mg": 475.0,
            "sodium_mg": 36.0,
            "zinc_mg": 0.3,
            "manganese_mg": 0.5,
            "selenium_mcg": 0.2,
            "vitamin_a_mcg": 961.0,
            "vitamin_c_mg": 19.6,
            "vitamin_e_mg": 0.7,
            "thiamin_mg": 0.11,
            "niacin_mg": 1.5,
            "vitamin_b6_mg": 0.29,
            "folate_mcg": 6.0,
            "choline_mg": 13.0,
        },
    },

    # ── Legumes ───────────────────────────────────────────────────────────
    "lentils cooked": {
        "calories_kcal": 116.0,
        "protein_g": 9.0,
        "carbs_g": 20.1,
        "fat_g": 0.4,
        "fiber_g": 7.9,
        "micronutrients": {
            "calcium_mg": 19.0,
            "iron_mg": 3.3,
            "magnesium_mg": 36.0,
            "phosphorus_mg": 180.0,
            "potassium_mg": 369.0,
            "sodium_mg": 2.0,
            "zinc_mg": 1.3,
            "copper_mg": 0.25,
            "manganese_mg": 0.49,
            "selenium_mcg": 2.8,
            "thiamin_mg": 0.17,
            "riboflavin_mg": 0.07,
            "niacin_mg": 1.1,
            "vitamin_b6_mg": 0.18,
            "folate_mcg": 181.0,
            "choline_mg": 32.7,
        },
    },
    "chickpeas cooked": {
        "calories_kcal": 164.0,
        "protein_g": 8.9,
        "carbs_g": 27.4,
        "fat_g": 2.6,
        "fiber_g": 7.6,
        "micronutrients": {
            "calcium_mg": 49.0,
            "iron_mg": 2.9,
            "magnesium_mg": 48.0,
            "phosphorus_mg": 168.0,
            "potassium_mg": 291.0,
            "sodium_mg": 7.0,
            "zinc_mg": 1.5,
            "copper_mg": 0.35,
            "manganese_mg": 1.0,
            "selenium_mcg": 3.7,
            "vitamin_a_mcg": 1.0,
            "vitamin_c_mg": 1.3,
            "thiamin_mg": 0.12,
            "riboflavin_mg": 0.06,
            "niacin_mg": 0.53,
            "vitamin_b6_mg": 0.14,
            "folate_mcg": 172.0,
            "choline_mg": 42.8,
        },
    },
    "black beans cooked": {
        "calories_kcal": 132.0,
        "protein_g": 8.9,
        "carbs_g": 23.7,
        "fat_g": 0.5,
        "fiber_g": 8.7,
        "micronutrients": {
            "calcium_mg": 27.0,
            "iron_mg": 2.1,
            "magnesium_mg": 70.0,
            "phosphorus_mg": 140.0,
            "potassium_mg": 355.0,
            "sodium_mg": 1.0,
            "zinc_mg": 1.1,
            "copper_mg": 0.21,
            "manganese_mg": 0.44,
            "selenium_mcg": 1.2,
            "thiamin_mg": 0.24,
            "niacin_mg": 0.51,
            "vitamin_b6_mg": 0.07,
            "folate_mcg": 149.0,
            "choline_mg": 32.6,
        },
    },
    "edamame": {
        "calories_kcal": 121.0,
        "protein_g": 11.9,
        "carbs_g": 8.9,
        "fat_g": 5.2,
        "fiber_g": 5.2,
        "micronutrients": {
            "calcium_mg": 63.0,
            "iron_mg": 2.3,
            "magnesium_mg": 64.0,
            "phosphorus_mg": 169.0,
            "potassium_mg": 436.0,
            "sodium_mg": 6.0,
            "zinc_mg": 1.4,
            "copper_mg": 0.36,
            "manganese_mg": 1.0,
            "vitamin_c_mg": 6.1,
            "vitamin_k_mcg": 26.7,
            "thiamin_mg": 0.2,
            "riboflavin_mg": 0.16,
            "niacin_mg": 1.0,
            "folate_mcg": 311.0,
            "choline_mg": 56.0,
        },
    },

    # ── Vegetables ────────────────────────────────────────────────────────
    "broccoli cooked": {
        "calories_kcal": 35.0,
        "protein_g": 2.4,
        "carbs_g": 7.2,
        "fat_g": 0.4,
        "fiber_g": 3.3,
        "micronutrients": {
            "calcium_mg": 40.0,
            "iron_mg": 0.7,
            "magnesium_mg": 21.0,
            "phosphorus_mg": 67.0,
            "potassium_mg": 293.0,
            "sodium_mg": 41.0,
            "zinc_mg": 0.45,
            "manganese_mg": 0.19,
            "selenium_mcg": 1.6,
            "vitamin_a_mcg": 77.0,
            "vitamin_c_mg": 64.9,
            "vitamin_e_mg": 1.5,
            "vitamin_k_mcg": 141.0,
            "thiamin_mg": 0.06,
            "riboflavin_mg": 0.12,
            "niacin_mg": 0.55,
            "vitamin_b6_mg": 0.2,
            "folate_mcg": 108.0,
            "choline_mg": 40.0,
        },
    },
    "spinach raw": {
        "calories_kcal": 23.0,
        "protein_g": 2.9,
        "carbs_g": 3.6,
        "fat_g": 0.4,
        "fiber_g": 2.2,
        "micronutrients": {
            "calcium_mg": 99.0,
            "iron_mg": 2.7,
            "magnesium_mg": 79.0,
            "phosphorus_mg": 49.0,
            "potassium_mg": 558.0,
            "sodium_mg": 79.0,
            "zinc_mg": 0.53,
            "manganese_mg": 0.9,
            "selenium_mcg": 1.0,
            "vitamin_a_mcg": 469.0,
            "vitamin_c_mg": 28.1,
            "vitamin_e_mg": 2.0,
            "vitamin_k_mcg": 483.0,
            "thiamin_mg": 0.08,
            "riboflavin_mg": 0.19,
            "niacin_mg": 0.72,
            "vitamin_b6_mg": 0.19,
            "folate_mcg": 194.0,
            "choline_mg": 19.3,
        },
    },
    "kale raw": {
        "calories_kcal": 43.0,
        "protein_g": 2.9,
        "carbs_g": 8.8,
        "fat_g": 0.9,
        "fiber_g": 3.6,
        "micronutrients": {
            "calcium_mg": 150.0,
            "iron_mg": 1.5,
            "magnesium_mg": 47.0,
            "phosphorus_mg": 92.0,
            "potassium_mg": 491.0,
            "sodium_mg": 38.0,
            "zinc_mg": 0.56,
            "manganese_mg": 0.66,
            "selenium_mcg": 0.9,
            "vitamin_a_mcg": 500.0,
            "vitamin_c_mg": 120.0,
            "vitamin_e_mg": 1.5,
            "vitamin_k_mcg": 817.0,
            "thiamin_mg": 0.11,
            "riboflavin_mg": 0.13,
            "niacin_mg": 1.0,
            "vitamin_b6_mg": 0.27,
            "folate_mcg": 141.0,
            "choline_mg": 0.5,
        },
    },
    "bell pepper red raw": {
        "calories_kcal": 31.0,
        "protein_g": 1.0,
        "carbs_g": 6.0,
        "fat_g": 0.3,
        "fiber_g": 2.1,
        "micronutrients": {
            "calcium_mg": 7.0,
            "iron_mg": 0.4,
            "magnesium_mg": 12.0,
            "phosphorus_mg": 26.0,
            "potassium_mg": 211.0,
            "sodium_mg": 4.0,
            "zinc_mg": 0.25,
            "manganese_mg": 0.11,
            "vitamin_a_mcg": 157.0,
            "vitamin_c_mg": 128.0,
            "vitamin_e_mg": 1.6,
            "vitamin_k_mcg": 4.9,
            "vitamin_b6_mg": 0.29,
            "folate_mcg": 46.0,
        },
    },
    "carrot raw": {
        "calories_kcal": 41.0,
        "protein_g": 0.9,
        "carbs_g": 9.6,
        "fat_g": 0.2,
        "fiber_g": 2.8,
        "micronutrients": {
            "calcium_mg": 33.0,
            "iron_mg": 0.3,
            "magnesium_mg": 12.0,
            "phosphorus_mg": 35.0,
            "potassium_mg": 320.0,
            "sodium_mg": 69.0,
            "zinc_mg": 0.24,
            "manganese_mg": 0.14,
            "vitamin_a_mcg": 835.0,
            "vitamin_c_mg": 5.9,
            "vitamin_e_mg": 0.66,
            "vitamin_k_mcg": 13.2,
            "thiamin_mg": 0.07,
            "niacin_mg": 1.0,
            "vitamin_b6_mg": 0.14,
            "folate_mcg": 19.0,
            "choline_mg": 8.8,
        },
    },
    "tomato raw": {
        "calories_kcal": 18.0,
        "protein_g": 0.9,
        "carbs_g": 3.9,
        "fat_g": 0.2,
        "fiber_g": 1.2,
        "micronutrients": {
            "calcium_mg": 10.0,
            "iron_mg": 0.3,
            "magnesium_mg": 11.0,
            "phosphorus_mg": 24.0,
            "potassium_mg": 237.0,
            "sodium_mg": 5.0,
            "zinc_mg": 0.17,
            "manganese_mg": 0.11,
            "vitamin_a_mcg": 42.0,
            "vitamin_c_mg": 13.7,
            "vitamin_e_mg": 0.54,
            "vitamin_k_mcg": 7.9,
            "vitamin_b6_mg": 0.08,
            "folate_mcg": 15.0,
            "choline_mg": 6.7,
        },
    },
    "cauliflower cooked": {
        "calories_kcal": 23.0,
        "protein_g": 1.8,
        "carbs_g": 4.1,
        "fat_g": 0.5,
        "fiber_g": 2.3,
        "micronutrients": {
            "calcium_mg": 16.0,
            "iron_mg": 0.3,
            "magnesium_mg": 9.0,
            "phosphorus_mg": 32.0,
            "potassium_mg": 142.0,
            "sodium_mg": 15.0,
            "zinc_mg": 0.17,
            "manganese_mg": 0.13,
            "vitamin_c_mg": 44.3,
            "vitamin_k_mcg": 13.8,
            "vitamin_b6_mg": 0.17,
            "folate_mcg": 44.0,
            "choline_mg": 39.1,
        },
    },
    "asparagus cooked": {
        "calories_kcal": 22.0,
        "protein_g": 2.4,
        "carbs_g": 4.1,
        "fat_g": 0.2,
        "fiber_g": 2.0,
        "micronutrients": {
            "calcium_mg": 23.0,
            "iron_mg": 0.9,
            "magnesium_mg": 14.0,
            "phosphorus_mg": 54.0,
            "potassium_mg": 224.0,
            "sodium_mg": 14.0,
            "zinc_mg": 0.6,
            "copper_mg": 0.16,
            "manganese_mg": 0.16,
            "selenium_mcg": 6.1,
            "vitamin_a_mcg": 50.0,
            "vitamin_c_mg": 7.7,
            "vitamin_e_mg": 1.5,
            "vitamin_k_mcg": 50.6,
            "thiamin_mg": 0.16,
            "riboflavin_mg": 0.14,
            "niacin_mg": 1.1,
            "vitamin_b6_mg": 0.08,
            "folate_mcg": 149.0,
            "choline_mg": 26.0,
        },
    },
    "bok choy cooked": {
        "calories_kcal": 12.0,
        "protein_g": 1.6,
        "carbs_g": 1.8,
        "fat_g": 0.2,
        "fiber_g": 1.0,
        "micronutrients": {
            "calcium_mg": 93.0,
            "iron_mg": 0.7,
            "magnesium_mg": 11.0,
            "phosphorus_mg": 29.0,
            "potassium_mg": 252.0,
            "sodium_mg": 34.0,
            "zinc_mg": 0.15,
            "vitamin_a_mcg": 180.0,
            "vitamin_c_mg": 26.0,
            "vitamin_k_mcg": 34.0,
            "folate_mcg": 68.0,
            "choline_mg": 12.0,
        },
    },
    "mixed greens": {
        "calories_kcal": 17.0,
        "protein_g": 1.5,
        "carbs_g": 2.9,
        "fat_g": 0.2,
        "fiber_g": 1.8,
        "micronutrients": {
            "calcium_mg": 50.0,
            "iron_mg": 1.2,
            "magnesium_mg": 20.0,
            "potassium_mg": 300.0,
            "vitamin_a_mcg": 200.0,
            "vitamin_c_mg": 18.0,
            "vitamin_k_mcg": 150.0,
            "folate_mcg": 80.0,
        },
    },

    # ── Fruits ────────────────────────────────────────────────────────────
    "banana": {
        "calories_kcal": 89.0,
        "protein_g": 1.1,
        "carbs_g": 22.8,
        "fat_g": 0.3,
        "fiber_g": 2.6,
        "micronutrients": {
            "calcium_mg": 5.0,
            "iron_mg": 0.26,
            "magnesium_mg": 27.0,
            "phosphorus_mg": 22.0,
            "potassium_mg": 358.0,
            "sodium_mg": 1.0,
            "zinc_mg": 0.15,
            "manganese_mg": 0.27,
            "vitamin_c_mg": 8.7,
            "vitamin_b6_mg": 0.37,
            "folate_mcg": 20.0,
            "choline_mg": 9.8,
        },
    },
    "blueberries": {
        "calories_kcal": 57.0,
        "protein_g": 0.7,
        "carbs_g": 14.5,
        "fat_g": 0.3,
        "fiber_g": 2.4,
        "micronutrients": {
            "calcium_mg": 6.0,
            "iron_mg": 0.28,
            "magnesium_mg": 6.0,
            "phosphorus_mg": 12.0,
            "potassium_mg": 77.0,
            "sodium_mg": 1.0,
            "zinc_mg": 0.16,
            "manganese_mg": 0.34,
            "vitamin_c_mg": 9.7,
            "vitamin_e_mg": 0.57,
            "vitamin_k_mcg": 19.3,
        },
    },
    "apple": {
        "calories_kcal": 52.0,
        "protein_g": 0.3,
        "carbs_g": 13.8,
        "fat_g": 0.2,
        "fiber_g": 2.4,
        "micronutrients": {
            "calcium_mg": 6.0,
            "iron_mg": 0.12,
            "magnesium_mg": 5.0,
            "phosphorus_mg": 11.0,
            "potassium_mg": 107.0,
            "sodium_mg": 1.0,
            "vitamin_c_mg": 4.6,
            "vitamin_k_mcg": 2.2,
            "choline_mg": 3.4,
        },
    },
    "avocado": {
        "calories_kcal": 160.0,
        "protein_g": 2.0,
        "carbs_g": 8.5,
        "fat_g": 14.7,
        "fiber_g": 6.7,
        "micronutrients": {
            "calcium_mg": 12.0,
            "iron_mg": 0.55,
            "magnesium_mg": 29.0,
            "phosphorus_mg": 52.0,
            "potassium_mg": 485.0,
            "sodium_mg": 7.0,
            "zinc_mg": 0.64,
            "copper_mg": 0.19,
            "manganese_mg": 0.14,
            "vitamin_a_mcg": 7.0,
            "vitamin_c_mg": 10.0,
            "vitamin_e_mg": 2.1,
            "vitamin_k_mcg": 21.0,
            "thiamin_mg": 0.07,
            "riboflavin_mg": 0.13,
            "niacin_mg": 1.7,
            "vitamin_b6_mg": 0.26,
            "folate_mcg": 81.0,
            "choline_mg": 14.2,
        },
    },
    "strawberries": {
        "calories_kcal": 32.0,
        "protein_g": 0.7,
        "carbs_g": 7.7,
        "fat_g": 0.3,
        "fiber_g": 2.0,
        "micronutrients": {
            "calcium_mg": 16.0,
            "iron_mg": 0.41,
            "magnesium_mg": 13.0,
            "phosphorus_mg": 24.0,
            "potassium_mg": 153.0,
            "sodium_mg": 1.0,
            "zinc_mg": 0.14,
            "manganese_mg": 0.39,
            "vitamin_c_mg": 58.8,
            "vitamin_k_mcg": 2.2,
            "folate_mcg": 24.0,
        },
    },
    "orange": {
        "calories_kcal": 47.0,
        "protein_g": 0.9,
        "carbs_g": 11.8,
        "fat_g": 0.1,
        "fiber_g": 2.4,
        "micronutrients": {
            "calcium_mg": 40.0,
            "iron_mg": 0.1,
            "magnesium_mg": 10.0,
            "phosphorus_mg": 14.0,
            "potassium_mg": 181.0,
            "sodium_mg": 0.0,
            "vitamin_a_mcg": 11.0,
            "vitamin_c_mg": 53.2,
            "thiamin_mg": 0.09,
            "folate_mcg": 30.0,
            "choline_mg": 8.4,
        },
    },

    # ── Nuts & Seeds ──────────────────────────────────────────────────────
    "almonds": {
        "calories_kcal": 579.0,
        "protein_g": 21.2,
        "carbs_g": 21.6,
        "fat_g": 49.9,
        "fiber_g": 12.5,
        "micronutrients": {
            "calcium_mg": 269.0,
            "iron_mg": 3.7,
            "magnesium_mg": 270.0,
            "phosphorus_mg": 481.0,
            "potassium_mg": 733.0,
            "sodium_mg": 1.0,
            "zinc_mg": 3.1,
            "copper_mg": 1.03,
            "manganese_mg": 2.18,
            "selenium_mcg": 4.1,
            "vitamin_e_mg": 25.6,
            "thiamin_mg": 0.21,
            "riboflavin_mg": 1.14,
            "niacin_mg": 3.6,
            "vitamin_b6_mg": 0.14,
            "folate_mcg": 44.0,
            "choline_mg": 52.1,
        },
    },
    "walnuts": {
        "calories_kcal": 654.0,
        "protein_g": 15.2,
        "carbs_g": 13.7,
        "fat_g": 65.2,
        "fiber_g": 6.7,
        "micronutrients": {
            "calcium_mg": 98.0,
            "iron_mg": 2.9,
            "magnesium_mg": 158.0,
            "phosphorus_mg": 346.0,
            "potassium_mg": 441.0,
            "sodium_mg": 2.0,
            "zinc_mg": 3.1,
            "copper_mg": 1.59,
            "manganese_mg": 3.41,
            "selenium_mcg": 4.9,
            "vitamin_e_mg": 0.7,
            "vitamin_b6_mg": 0.54,
            "folate_mcg": 98.0,
            "choline_mg": 39.2,
            "omega3_ala_mg": 9080.0,
        },
    },
    "almond butter": {
        "calories_kcal": 614.0,
        "protein_g": 21.0,
        "carbs_g": 18.8,
        "fat_g": 55.5,
        "fiber_g": 10.5,
        "micronutrients": {
            "calcium_mg": 347.0,
            "iron_mg": 3.5,
            "magnesium_mg": 279.0,
            "phosphorus_mg": 508.0,
            "potassium_mg": 748.0,
            "sodium_mg": 7.0,
            "zinc_mg": 3.3,
            "copper_mg": 0.96,
            "manganese_mg": 1.8,
            "vitamin_e_mg": 24.2,
            "riboflavin_mg": 0.94,
            "niacin_mg": 3.1,
            "folate_mcg": 53.0,
            "choline_mg": 52.0,
        },
    },
    "chia seeds": {
        "calories_kcal": 486.0,
        "protein_g": 16.5,
        "carbs_g": 42.1,
        "fat_g": 30.7,
        "fiber_g": 34.4,
        "micronutrients": {
            "calcium_mg": 631.0,
            "iron_mg": 7.7,
            "magnesium_mg": 335.0,
            "phosphorus_mg": 860.0,
            "potassium_mg": 407.0,
            "sodium_mg": 16.0,
            "zinc_mg": 4.6,
            "copper_mg": 0.92,
            "manganese_mg": 2.72,
            "selenium_mcg": 55.2,
            "thiamin_mg": 0.62,
            "riboflavin_mg": 0.17,
            "niacin_mg": 8.83,
            "folate_mcg": 49.0,
            "omega3_ala_mg": 17830.0,
        },
    },
    "flaxseed": {
        "calories_kcal": 534.0,
        "protein_g": 18.3,
        "carbs_g": 28.9,
        "fat_g": 42.2,
        "fiber_g": 27.3,
        "micronutrients": {
            "calcium_mg": 255.0,
            "iron_mg": 5.7,
            "magnesium_mg": 392.0,
            "phosphorus_mg": 642.0,
            "potassium_mg": 813.0,
            "sodium_mg": 30.0,
            "zinc_mg": 4.3,
            "copper_mg": 1.22,
            "manganese_mg": 2.48,
            "selenium_mcg": 25.4,
            "thiamin_mg": 1.64,
            "riboflavin_mg": 0.16,
            "niacin_mg": 3.08,
            "vitamin_b6_mg": 0.47,
            "folate_mcg": 87.0,
            "choline_mg": 78.7,
            "omega3_ala_mg": 22810.0,
        },
    },

    # ── Oils & Other ──────────────────────────────────────────────────────
    "olive oil": {
        "calories_kcal": 884.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 100.0,
        "fiber_g": 0.0,
        "micronutrients": {
            "vitamin_e_mg": 14.35,
            "vitamin_k_mcg": 60.2,
            "iron_mg": 0.56,
        },
    },
    "coconut oil": {
        "calories_kcal": 862.0,
        "protein_g": 0.0,
        "carbs_g": 0.0,
        "fat_g": 100.0,
        "fiber_g": 0.0,
        "micronutrients": {
            "vitamin_e_mg": 0.09,
        },
    },
    "honey": {
        "calories_kcal": 304.0,
        "protein_g": 0.3,
        "carbs_g": 82.4,
        "fat_g": 0.0,
        "fiber_g": 0.2,
        "micronutrients": {
            "calcium_mg": 6.0,
            "iron_mg": 0.42,
            "magnesium_mg": 2.0,
            "phosphorus_mg": 4.0,
            "potassium_mg": 52.0,
            "sodium_mg": 4.0,
            "zinc_mg": 0.22,
            "manganese_mg": 0.08,
            "vitamin_c_mg": 0.5,
        },
    },
    "dark chocolate 70": {
        "calories_kcal": 598.0,
        "protein_g": 7.8,
        "carbs_g": 45.9,
        "fat_g": 42.6,
        "fiber_g": 10.9,
        "micronutrients": {
            "calcium_mg": 73.0,
            "iron_mg": 11.9,
            "magnesium_mg": 228.0,
            "phosphorus_mg": 308.0,
            "potassium_mg": 715.0,
            "sodium_mg": 20.0,
            "zinc_mg": 3.3,
            "copper_mg": 1.77,
            "manganese_mg": 1.95,
            "selenium_mcg": 6.8,
            "vitamin_k_mcg": 7.3,
            "thiamin_mg": 0.03,
            "riboflavin_mg": 0.08,
            "niacin_mg": 1.05,
            "vitamin_b6_mg": 0.04,
        },
    },
    "sourdough bread": {
        "calories_kcal": 274.0,
        "protein_g": 10.7,
        "carbs_g": 51.9,
        "fat_g": 2.4,
        "fiber_g": 2.4,
        "micronutrients": {
            "calcium_mg": 56.0,
            "iron_mg": 2.8,
            "magnesium_mg": 26.0,
            "phosphorus_mg": 97.0,
            "potassium_mg": 117.0,
            "sodium_mg": 602.0,
            "zinc_mg": 0.9,
            "selenium_mcg": 22.5,
            "thiamin_mg": 0.36,
            "riboflavin_mg": 0.22,
            "niacin_mg": 3.6,
            "folate_mcg": 97.0,
        },
    },
}

# ---------------------------------------------------------------------------
# Aliases — maps common user input to canonical catalog keys
# ---------------------------------------------------------------------------

INGREDIENT_ALIASES: dict[str, str] = {
    # Proteins
    "chicken breast": "chicken breast cooked",
    "chicken": "chicken breast cooked",
    "grilled chicken": "chicken breast cooked",
    "grilled chicken breast": "chicken breast cooked",
    "salmon": "salmon atlantic raw",
    "ground beef": "beef ground 85 15 cooked",
    "beef": "beef ground 85 15 cooked",
    "tofu": "tofu firm",
    "shrimp": "shrimp cooked",
    "prawns": "shrimp cooked",
    "pork": "pork loin cooked",
    "pork loin": "pork loin cooked",
    "turkey": "turkey breast cooked",
    "turkey breast": "turkey breast cooked",
    "tuna": "tuna canned in water",
    "canned tuna": "tuna canned in water",
    # Eggs & dairy
    "egg": "egg whole raw",
    "eggs": "egg whole raw",
    "scrambled eggs": "egg whole raw",
    "greek yogurt": "greek yogurt plain",
    "yogurt": "greek yogurt plain",
    "cottage cheese": "cottage cheese low fat",
    "milk": "milk whole",
    "whole milk": "milk whole",
    "cheddar": "cheddar cheese",
    "cheese": "cheddar cheese",
    # Grains
    "white rice": "rice white cooked",
    "rice": "rice white cooked",
    "jasmine rice": "rice white cooked",
    "brown rice": "rice brown cooked",
    "oatmeal": "oats",
    "oat": "oats",
    "rolled oats": "oats",
    "quinoa": "quinoa cooked",
    "whole wheat bread": "bread whole wheat",
    "wheat bread": "bread whole wheat",
    "pasta": "pasta cooked",
    "spaghetti": "pasta cooked",
    "sweet potato": "sweet potato baked",
    # Legumes
    "lentils": "lentils cooked",
    "lentil": "lentils cooked",
    "lentil soup": "lentils cooked",
    "chickpeas": "chickpeas cooked",
    "garbanzo beans": "chickpeas cooked",
    "black beans": "black beans cooked",
    # Vegetables
    "broccoli": "broccoli cooked",
    "spinach": "spinach raw",
    "kale": "kale raw",
    "red pepper": "bell pepper red raw",
    "bell pepper": "bell pepper red raw",
    "carrot": "carrot raw",
    "carrots": "carrot raw",
    "tomato": "tomato raw",
    "tomatoes": "tomato raw",
    "cauliflower": "cauliflower cooked",
    "asparagus": "asparagus cooked",
    "bok choy": "bok choy cooked",
    "salad": "mixed greens",
    "lettuce": "mixed greens",
    "mixed green salad": "mixed greens",
    # Fruits
    "bananas": "banana",
    "blueberry": "blueberries",
    "apples": "apple",
    "avocados": "avocado",
    "strawberry": "strawberries",
    "oranges": "orange",
    # Nuts & seeds
    "almond": "almonds",
    "walnut": "walnuts",
    "chia": "chia seeds",
    "flax": "flaxseed",
    "flax seeds": "flaxseed",
    "flaxseeds": "flaxseed",
    # Oils & other
    "olive oil extra virgin": "olive oil",
    "evoo": "olive oil",
    "dark chocolate": "dark chocolate 70",
    "sourdough": "sourdough bread",
    # Chinese aliases
    "鸡蛋": "egg whole raw",
    "三文鱼": "salmon atlantic raw",
    "鸡胸肉": "chicken breast cooked",
    "牛肉": "beef ground 85 15 cooked",
    "豆腐": "tofu firm",
    "虾": "shrimp cooked",
    "米饭": "rice white cooked",
    "白米饭": "rice white cooked",
    "糙米": "rice brown cooked",
    "燕麦": "oats",
    "西兰花": "broccoli cooked",
    "菠菜": "spinach raw",
    "番茄": "tomato raw",
    "香蕉": "banana",
    "牛油果": "avocado",
}

# ---------------------------------------------------------------------------
# Portion shortcuts — maps user-friendly portion strings to grams
# ---------------------------------------------------------------------------

PORTION_GRAMS: dict[str, dict[str, float]] = {
    "egg whole raw": {
        "1 egg": 50.0,
        "2 eggs": 100.0,
        "3 eggs": 150.0,
    },
    "rice white cooked": {
        "1 bowl": 158.0,
        "1 cup": 158.0,
    },
    "rice brown cooked": {
        "1 bowl": 195.0,
        "1 cup": 195.0,
    },
    "oats": {
        "1 bowl": 40.0,
        "1 cup": 80.0,
    },
    "quinoa cooked": {
        "1 cup": 185.0,
    },
    "pasta cooked": {
        "1 cup": 140.0,
        "1 serving": 140.0,
    },
    "greek yogurt plain": {
        "1 cup": 245.0,
        "1 container": 170.0,
    },
    "milk whole": {
        "1 cup": 244.0,
        "1 glass": 244.0,
    },
    "banana": {
        "1 banana": 118.0,
        "1 medium": 118.0,
    },
    "apple": {
        "1 apple": 182.0,
        "1 medium": 182.0,
    },
    "orange": {
        "1 orange": 131.0,
        "1 medium": 131.0,
    },
    "avocado": {
        "1 avocado": 150.0,
        "1/2 avocado": 75.0,
        "1/4 avocado": 37.5,
    },
    "bread whole wheat": {
        "1 slice": 28.0,
        "2 slices": 56.0,
    },
    "sourdough bread": {
        "1 slice": 36.0,
        "2 slices": 72.0,
    },
    "almonds": {
        "1 handful": 28.0,
        "1 oz": 28.0,
    },
    "walnuts": {
        "1 handful": 28.0,
        "1 oz": 28.0,
    },
    "almond butter": {
        "1 tbsp": 16.0,
        "2 tbsp": 32.0,
    },
    "chia seeds": {
        "1 tbsp": 12.0,
        "2 tbsp": 24.0,
    },
    "flaxseed": {
        "1 tbsp": 7.0,
        "2 tbsp": 14.0,
    },
    "olive oil": {
        "1 tbsp": 14.0,
        "2 tbsp": 28.0,
    },
    "honey": {
        "1 tbsp": 21.0,
        "1 tsp": 7.0,
    },
    "cheddar cheese": {
        "1 slice": 28.0,
        "1 oz": 28.0,
    },
    "dark chocolate 70": {
        "1 square": 10.0,
        "1 oz": 28.0,
    },
    "blueberries": {
        "1 cup": 148.0,
        "1/2 cup": 74.0,
    },
    "strawberries": {
        "1 cup": 152.0,
        "1/2 cup": 76.0,
    },
    "chicken breast cooked": {
        "1 breast": 172.0,
    },
    "salmon atlantic raw": {
        "1 fillet": 170.0,
        "6 oz": 170.0,
    },
    "sweet potato baked": {
        "1 medium": 114.0,
    },
    "lentils cooked": {
        "1 cup": 198.0,
        "1 bowl": 250.0,
    },
    "chickpeas cooked": {
        "1 cup": 164.0,
    },
    "black beans cooked": {
        "1 cup": 172.0,
    },
    "tofu firm": {
        "1 block": 200.0,
        "1/2 block": 100.0,
    },
}
